### ISSUE TITLE
Výsledky

### ISSUE THREAD

**Issue by lahwaacz** [HelloWorld7894/GestureDetection#1]
Ahoj, nějak mi nepřišel email s vašimi výsledky (prezentace a sborník). Můžete to prosím zkusit znovu? Možná jsem včera adresu napsal špatně: `klinkjak cat fjfi cvut cz`
Taky bych vás všechny rád pozval na [podzimní hackathon](https://ksi.fjfi.cvut.cz/udalosti/hackathon-mlai) pořádaný naší katedrou v Děčíně :wink:

**Comment by HelloWorld7894** [comment]
Ahoj, vzhledem k tomu že nám moc to posílání přes mail nejde (snažil jsem se dostat k prezentaci od Mirkovo mailu ale nechtělo mě to pustit), tak dávám prezentaci a příspěvek do sborníku sem na github, aby se k němu dostal každý. 
Odkazy na ně najdeš v `README.md`

Jo a na hackathon určitě přijdu 😃.
